name: checkstyle
on: [pull_request, push]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain --no-daemon --stacktrace